# -*- coding: utf-8 -*-
"""Perceptron.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LNq68VyugMA0rfNRLPRknS4fjhaJcfkQ
"""

import numpy as np
import pandas as pd
from sklearn.datasets import make_classification
from sklearn.metrics import r2_score

df=pd.read_csv("/content/gender_classification_v7.csv")

df.shape

df.info()

df.isnull().sum()

df.describe()

df.head()

df.columns

# Female=0 and male=1
df['gender'].replace('Female',0,inplace=True)
df['gender'].replace('Male',1,inplace=True)

df.head(5)

df.shape

X=df.iloc[:,:7]
y=df.iloc[:,-1]

X.shape

y.shape

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=4)

X_train.shape,y_train.shape,X_test.shape,y_test.shape

from sklearn.linear_model import Perceptron

p=Perceptron()

p.fit(X_train,y_train)

p.score(X_test,y_test)

ypred=p.predict(X_test)

ypred.shape

r2_score(y_test,ypred)

